//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//fetch
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const SELECTED_WAY_TO_FILTER_COLUMN='SELECTED_WAY_TO_FILTER_COLUMN';
export const SELECTED_COLUMN_TO_FILTER='SELECTED_COLUMN_TO_FILTER';
export const CONFIRM_FILTER_WAY_TO_COLUMN='CONFIRM_FILTER_WAY_TO_COLUMN';
export const FILTER_FETCHED_DATA='FILTER_FETCHED_DATA';